
export const allBlogPosts = [
    {
      title: 'Reskilling vs. Upskilling: The Survival Guide for the Modern Indian Workforce',
      excerpt: 'Learn how to stay relevant in the Indian job market. Discover the difference between upskilling and reskilling and how to get data-backed career guidance.',
      href: '/blog/reskilling-vs-upskilling',
      date: '2026-01-01',
      tags: ['Upskilling', 'Reskilling', 'Future of Work', 'Career Growth'],
    },
    {
      title: 'Will AI Take My Job? How to Choose a Career That’s "Robot-Proof"',
      excerpt: 'Worried about AI taking your job? Discover the most stable, high-paying careers for the future and how to build a robot-proof career path.',
      href: '/blog/will-ai-take-my-job',
      date: '2025-12-30',
      tags: ['AI', 'Future of Work', 'Career Advice'],
    },
    {
      title: 'Passion or Salary? The Truth About Dream Careers in India',
      excerpt: 'Is it better to follow your passion or chase a high salary? Discover why the most successful careers in 2026 are the ones that combine both.',
      href: '/blog/passion-vs-salary',
      date: '2025-12-28',
      tags: ['Dream Career', 'Career Choice', 'India'],
    },
    {
      title: 'Career Counselling in India: Complete Guide for Students & Parents (2026)',
      excerpt: 'A complete guide to understanding the importance and process of career counselling in India for students and parents in 2026.',
      href: '/blog/career-counselling-in-india-guide',
      date: '2025-12-26',
      tags: ['Career Counselling', 'India', 'Students'],
    },
    {
      title: 'Is Career Counselling Worth It? An Honest, Data-Backed Answer',
      excerpt: 'Explore the real value of career counselling. Is it just motivational talk, or a crucial investment? We look at the data to find out.',
      href: '/blog/is-career-counselling-worth-it',
      date: '2025-12-24',
      tags: ['Career Counselling', 'Career Advice'],
    },
    {
      title: 'AI Career Counselling vs. Human Counsellors: What Actually Works?',
      excerpt: 'AI is transforming career guidance. We compare AI-powered counselling with traditional human counsellors to see what works best in 2026.',
      href: '/blog/ai-vs-human-career-counselling',
      date: '2025-12-22',
      tags: ['AI', 'Career Counselling', 'Technology'],
    },
    {
      title: 'Career Counselling After 10th: 5 Mistakes 90% of Students Make',
      excerpt: 'Class 10 is a critical stage for career decisions. Learn about the common mistakes students make when choosing a stream and how to avoid them.',
      href: '/blog/career-counselling-after-10th-mistakes',
      date: '2025-12-20',
      tags: ['Career Counselling', 'Students', '10th Grade'],
    },
    {
      title: 'Career Counselling After 12th: A Guide for Science, Commerce, and Arts Students',
      excerpt: 'The decision after 12th grade can define your career. This guide covers the options and confusion for students from all streams.',
      href: '/blog/career-counselling-after-12th-streams',
      date: '2025-12-18',
      tags: ['Career Counselling', 'Students', '12th Grade'],
    },
    {
      title: 'How to Find Your Dream Career (Without Ruining Your Life)',
      excerpt: 'Stop gambling with your future. Learn how to find a career you love using AI-driven data without risking your financial stability.',
      href: '/blog/find-your-dream-career',
      date: '2025-12-16',
      tags: ['Dream Career', 'Career Choice', 'Career Advice'],
    },
    {
      title: 'Dream Career vs. Reality: The Honest Truth',
      excerpt: 'What is the reality of following your passion? Learn the 80/20 rule of dream jobs and how to find a path that actually works in the real world.',
      href: '/blog/dream-career-vs-reality',
      date: '2025-12-14',
      tags: ['Dream Career', 'Passion vs Profession', 'Career Advice'],
    },
    {
      title: 'Why Most People Never Find Their Dream Career',
      excerpt: 'Discover the psychological traps like Analysis Paralysis and the Sunk Cost Fallacy that prevent you from finding your dream job.',
      href: '/blog/why-most-people-never-find-their-dream-career',
      date: '2025-12-12',
      tags: ['Dream Career', 'Psychology', 'Career Change'],
    },
    {
      title: 'How to Choose the Right Career in 2025',
      excerpt: 'A modern guide to choosing the right career. Learn how to balance your passions, skills, and market demand to find a fulfilling and future-proof job path with the help of AI.',
      href: '/blog/how-to-choose-the-right-career',
      date: '2025-12-10',
      tags: ['Career Choice', 'Career Guidance', '2025'],
    },
    {
      title: 'Are Career Tests Accurate? A Look at AI-Powered Assessments',
      excerpt: 'Explore the accuracy of career tests, from traditional personality quizzes to modern AI-powered career assessments and data-driven guidance.',
      href: '/blog/are-career-tests-accurate',
      date: '2025-12-08',
      tags: ['Career Tests', 'AI', 'Accuracy'],
    },
    {
      title: 'Which Career Is Best for Students? A Clear Guide to Choosing the Right Career',
      excerpt: 'Struggling with career confusion as a student? Learn how to find a path that aligns with your skills, interests, and personality using data-driven insights.',
      href: '/blog/which-career-is-best-for-students',
      date: '2025-12-06',
      tags: ['Students', 'Career Guidance', 'Career Choice'],
    },
    {
      title: 'What Is the Best Career Move for Working Professionals Feeling Stuck?',
      excerpt: 'Feeling stuck, underpaid, or unfulfilled in your job? The best career move is not quitting blindly—it’s making a strategic, informed transition.',
      href: '/blog/best-career-move-for-working-professionals',
      date: '2025-12-04',
      tags: ['Working Professionals', 'Career Change', 'Career Growth'],
    },
    {
      title: 'Best Career Options for 2026: How to Future-Proof Your Career',
      excerpt: "The job market is changing fast. To succeed in 2026 and beyond, choosing a future-proof career is essential. Here's how.",
      href: '/blog/best-career-options-for-2026',
      date: '2025-12-02',
      tags: ['2026', 'Future of Work', 'Career Options'],
    },
    {
      title: 'Which Career Is Best for Me? A Data-Driven Guide',
      excerpt: 'Feeling lost about your career? This guide helps you answer "Which career is best for me?" by focusing on a data-driven approach using AI-powered career assessments.',
      href: '/blog/which-career-is-best-for-me',
      date: '2025-12-01',
      tags: ['Career Choice', 'Career Guidance', 'Self-Assessment'],
    },
];
