export interface Question {
  id: number;
  text: string;
  options: string[];
}

export const psychometricTestQuestions: Question[] = [
  { id: 1, text: 'I enjoy solving complex problems.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 2, text: 'I prefer working independently rather than in a team.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 3, text: 'I am comfortable taking on leadership roles.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 4, text: 'I am detail-oriented and meticulous in my work.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 5, text: 'I enjoy creative tasks and brainstorming new ideas.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 6, text: 'I am comfortable with public speaking and presenting.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 7, text: 'I thrive in fast-paced and dynamic environments.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 8, text: 'I am good at organizing and planning tasks.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 9, text: 'I enjoy working with data and analyzing information.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 10, text: 'I am comfortable dealing with unpredictable situations.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 11, text: 'I am patient and enjoy helping others learn.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 12, text: 'I am comfortable working with my hands and building things.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 13, text: 'I enjoy conducting research and exploring new topics.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 14, text: 'I am persuasive and good at negotiating.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 15, text: 'I am comfortable working with technology and computers.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 16, text: 'I enjoy being outdoors and working in nature.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 17, text: 'I am empathetic and good at understanding others\' feelings.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 18, text: 'I am comfortable working with numbers and financial data.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 19, text: 'I enjoy creating or performing art, music, or drama.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 20, text: 'I am good at resolving conflicts and mediating disagreements.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 21, text: 'I am comfortable working in a structured and organized environment.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 22, text: 'I enjoy taking risks and trying new things.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 23, text: 'I am patient and can work on long-term projects.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 24, text: 'I am good at written communication.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 25, text: 'I enjoy working with animals.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 26, text: 'I am comfortable working under pressure and meeting deadlines.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 27, text: 'I am good at visual design and aesthetics.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 28, text: 'I enjoy working in a healthcare setting.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 29, text: 'I am comfortable with repetitive tasks.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 30, text: 'I enjoy teaching and mentoring others.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 31, text: 'I am good at mechanical reasoning and understanding how things work.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 32, text: 'I enjoy working with the public and interacting with customers.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 33, text: 'I am comfortable conducting experiments and scientific research.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 34, text: 'I am good at managing budgets and financial resources.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 35, text: 'I enjoy working on projects that require precision.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 36, text: 'I am comfortable with physical labor.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 37, text: 'I am good at strategic thinking and planning for the future.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 38, text: 'I enjoy working in a legal or justice-related field.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 39, text: 'I am comfortable with sales and marketing activities.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 40, text: 'I enjoy working on projects that involve technology and innovation.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 41, text: 'I am good at troubleshooting and fixing problems.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 42, text: 'I enjoy working with children.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 43, text: 'I am comfortable with administrative tasks and record-keeping.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 44, text: 'I enjoy working in a manufacturing or production environment.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 45, text: 'I am good at interpreting complex information.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 46, text: 'I enjoy working in a hospitality or tourism setting.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 47, text: 'I am comfortable working with chemicals or biological materials.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 48, text: 'I am good at coaching and motivating others.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 49, text: 'I enjoy working on projects that have a social impact.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
  { id: 50, text: 'I am comfortable working with computer code and programming.', options: ['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'] },
];
